name: pr

on:
  pull_request:
    types:
    - synchronize
    - opened
    - reopened
    - ready_for_review
    - closed

jobs:
  test:
    if: github.event.action != 'closed'
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: make test
  build:
    if: github.event.pull_request.merged == true && github.event.action == 'closed'
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: File permission
      run: chmod +x scripts/get_version.sh
    - name: Build image
      run: make build
    - name: Login docker
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Push image to dockerhub
      run: make push
    # - name: Remote deployment with ssh
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.USERNAME }}
    #     password: ${{ secrets.PASSWORD }}
    #     port: ${{ secrets.PORT }}
    #     script: |
    #       echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    #       docker ps --filter status=running -q | xargs docker rm -f
    #       make run-docker
    - name: Deploy the pull request
      run: |
        # deployment logic goes here
        sleep 10
        # instead we return succeed directly
        exit 0